/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import clasesjava.ConexionDB;
import com.mycompany.mavenproject4.clasescomplemento.textoSombra;
import complemetos_.consultasUsuario;
import java.awt.Color;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Carlo
 */
public class Login extends javax.swing.JFrame {
    Color inv = new Color(0,0,0,0);

    /**
     * Creates new form NewJFrame
     */
    public Login() {
        initComponents();
        //botones Invisibles
        //btn Acceder
        btncrearUsuario.setVisible(true);
        btnReCon.setBackground(inv);
        btnReCon.setFocusPainted(false);
        //btn Recuperar Contraseña
        btnReCon.setVisible(true);
        btnReCon.setBackground(inv);
        btnReCon.setFocusPainted(false);
        this.setExtendedState(this.MAXIMIZED_BOTH);
        
        
        
        
        //Texto sobra
        //inicio de sesion
        textoSombra correoe = new textoSombra (" correoejemplo@gmail.com",txtCorreoInicioS);
        textoSombra corrcontra = new textoSombra (" Contraseña",txtContraseñaInicio);
        
    }
    
    
    
   
    
    private Connection obtenerConexion() {
        return ConexionDB.conectar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCorreoInicioS = new javax.swing.JTextField();
        btncrearUsuario = new javax.swing.JButton();
        btnReCon = new javax.swing.JButton();
        txtContraseñaInicio = new javax.swing.JPasswordField();
        btnAcceder1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(44, 116, 142));
        jPanel1.setForeground(new java.awt.Color(44, 116, 142));

        jPanel2.setBackground(new java.awt.Color(240, 249, 251));

        jLabel1.setFont(new java.awt.Font("Bernard MT Condensed", 0, 45)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(44, 116, 142));
        jLabel1.setText("Iniciar Sesion");

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Correo:");

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Contraseña:");

        txtCorreoInicioS.setBackground(new java.awt.Color(185, 196, 203));
        txtCorreoInicioS.setForeground(new java.awt.Color(44, 116, 142));
        txtCorreoInicioS.setBorder(null);
        txtCorreoInicioS.setSelectedTextColor(new java.awt.Color(44, 116, 142));
        txtCorreoInicioS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoInicioSActionPerformed(evt);
            }
        });

        btncrearUsuario.setBackground(new java.awt.Color(44, 116, 142));
        btncrearUsuario.setFont(new java.awt.Font("Bernard MT Condensed", 0, 18)); // NOI18N
        btncrearUsuario.setForeground(new java.awt.Color(255, 255, 255));
        btncrearUsuario.setText("Crear");
        btncrearUsuario.setBorder(null);
        btncrearUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncrearUsuarioActionPerformed(evt);
            }
        });

        btnReCon.setBackground(new java.awt.Color(240, 249, 251));
        btnReCon.setForeground(new java.awt.Color(44, 116, 142));
        btnReCon.setText("¿Recuperar Contraseña?");
        btnReCon.setBorder(null);
        btnReCon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReConActionPerformed(evt);
            }
        });

        txtContraseñaInicio.setBackground(new java.awt.Color(185, 196, 203));
        txtContraseñaInicio.setForeground(new java.awt.Color(44, 116, 142));
        txtContraseñaInicio.setBorder(null);

        btnAcceder1.setBackground(new java.awt.Color(44, 116, 142));
        btnAcceder1.setFont(new java.awt.Font("Bernard MT Condensed", 0, 18)); // NOI18N
        btnAcceder1.setForeground(new java.awt.Color(255, 255, 255));
        btnAcceder1.setText("Acceder");
        btnAcceder1.setBorder(null);
        btnAcceder1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcceder1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnAcceder1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                                .addComponent(btncrearUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtContraseñaInicio)
                            .addComponent(txtCorreoInicioS)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addComponent(btnReCon, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(212, 212, 212)
                        .addComponent(jLabel1)))
                .addGap(46, 112, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCorreoInicioS, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtContraseñaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAcceder1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncrearUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnReCon)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(116, 116, 116)
                .addComponent(jLabel6)
                .addContainerGap(88, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(138, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(90, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCorreoInicioSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoInicioSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoInicioSActionPerformed

    private void btncrearUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncrearUsuarioActionPerformed

    
        
    }//GEN-LAST:event_btncrearUsuarioActionPerformed
    
    
    private void btnReConActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReConActionPerformed

    
        
    }//GEN-LAST:event_btnReConActionPerformed

    private void btnAcceder1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcceder1ActionPerformed
                                            
    String email = txtCorreoInicioS.getText().trim();
    String password = new String(txtContraseñaInicio.getPassword()).trim();

    // Validar campos vacíos
    if (email.isEmpty() || password.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Por favor, complete todos los campos",
                "Advertencia", JOptionPane.WARNING_MESSAGE);
        return;
    }

    // Validar formato de email
    if (!email.matches("^[A-Za-z0-9+_.-]+@(.+)$")) {
        JOptionPane.showMessageDialog(this, "Formato de email inválido",
                "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    Connection conexion = obtenerConexion();
    if (conexion != null) {
        try {
            consultasUsuario consultas = new consultasUsuario(conexion);

            // Verificar credenciales
            if (consultas.verificarUsuario(email, password)) {
                // Obtener información del usuario
                String roles = consultas.obtenerRolesUsuario(email);
                int idUsuario = consultas.obtenerIdUsuario(email);

                // Mostrar mensaje de bienvenida
                JOptionPane.showMessageDialog(this,
                        "¡Bienvenido! \nID: " + idUsuario
                        + "\nEmail: " + email
                        + "\nRoles: " + roles,
                        "Acceso concedido",
                        JOptionPane.INFORMATION_MESSAGE);

                // ===== ABRIR EL MENÚ =====
                Menú menu = new Menú(); // <-- constructor con datos
                menu.setExtendedState(Menú.MAXIMIZED_BOTH);    // abrir maximizado
                menu.setLocationRelativeTo(null);              // centrar en pantalla
                menu.setVisible(true);

                this.dispose(); // cerrar login
            } else {
                JOptionPane.showMessageDialog(this,
                        "Credenciales incorrectas o usuario inactivo",
                        "Error de autenticación",
                        JOptionPane.ERROR_MESSAGE);
            }
        } finally {
            try {
                if (conexion != null) conexion.close();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Error al cerrar conexión: " + e.getMessage());
            }
        }
    } else {
        JOptionPane.showMessageDialog(this, "Error de conexión a la base de datos",
                "Error", JOptionPane.ERROR_MESSAGE);
    }

        
    }//GEN-LAST:event_btnAcceder1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcceder1;
    private javax.swing.JButton btnReCon;
    private javax.swing.JButton btncrearUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField txtContraseñaInicio;
    private javax.swing.JTextField txtCorreoInicioS;
    // End of variables declaration//GEN-END:variables
}
